name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch: null
env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    # 同時実行すると CREATE_IN_PROGRESS や UPDATE_IN_PROGRESS 状態で cdk deploy を行う可能性があるため抑止する
    concurrency:
      group: "cloudformation-llm-basic"
      cancel-in-progress: false

    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@v1

    - name: Install global dependency
      run: pnpm add -g esbuild

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/strands-agent-example-deploy-role
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: deploy
      working-directory: agent
      env:
        DATABRICKS_WORKSPACE_URL: ${{ secrets.DATABRICKS_WORKSPACE_URL }}
        DATABRICKS_OAUTH_CLIENT_ID: ${{ secrets.DATABRICKS_OAUTH_CLIENT_ID }}
        DATABRICKS_OAUTH_CLIENT_SECRET: ${{ secrets.DATABRICKS_OAUTH_CLIENT_SECRET }}
        DATABRICKS_UC_SCHEMA_NAME: ${{ secrets.DATABRICKS_UC_SCHEMA_NAME }}
        DATABRICKS_UC_TABLE_PREFIX: ${{ secrets.DATABRICKS_UC_TABLE_PREFIX }}
      run: |
        pnx aws-cdk@latest deploy \
          -c "databricks-workspace-url=$DATABRICKS_WORKSPACE_URL" \
          -c "databricks-oauth-client-id=$DATABRICKS_OAUTH_CLIENT_ID" \
          -c "databricks-oauth-client-secret=$DATABRICKS_OAUTH_CLIENT_SECRET" \
          -c "databricks-uc-schema-name=$DATABRICKS_UC_SCHEMA_NAME" \
          -c "databricks-uc-table-prefix=$DATABRICKS_UC_TABLE_PREFIX"
